- name: Instalar Docker no Ubuntu (LTS atual)
  hosts: vm
  become: yes
  tasks:
    - name: Instalar dependências
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Criar diretório para keyrings
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Baixar chave GPG oficial do Docker
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Converter chave GPG para formato keyring
      command: gpg --dearmor -o /etc/apt/keyrings/docker.gpg /etc/apt/keyrings/docker.asc
      args:
        creates: /etc/apt/keyrings/docker.gpg

    - name: Adicionar repositório oficial do Docker
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        state: present
        filename: docker

    - name: Atualizar cache do apt e instalar Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: Adicionar usuário ao grupo Docker
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Iniciar e habilitar o serviço Docker
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Executar container da aplicação Java
      community.docker.docker_container:
        name: java-api
        image: iesodias/java-api:latest
        state: started
        restart_policy: always
        published_ports:
          - "8081:8081"
